### ISSUE TITLE
JWT key handling in code does not correspond with blog resulting in execution errors

### ISSUE THREAD

**Issue by MXClyde** [aws-samples/lambdaedge-openidconnect-samples#12]
The blog on https://aws.amazon.com/blogs/networking-and-content-delivery/securing-cloudfront-distributions-using-openid-connect-and-aws-secrets-manager/ does not include PUBLIC_KEY and PRIVATE_KEY in the example  idP configuration secret. This causes the Lambda function to fail. It is not apparant to me in what format those keys should be provided in order for the function to execute correctly.

In the end I chose to distribute generated JWT private and public key files together with the Lambda function and refer to those files instead by changing line 88 in /src/js/auth.js into:

```
		var publicKey = fs.readFileSync('public.key');
		await verifyJwt(Cookie.parse(headers.cookie[0].value).TOKEN, publicKey, {
```

Inserting the following line after line 286 in /src/js/auth.js:

`	var privateKey = fs.readFileSync('private.key');`

And changing line 306 in /src/js/auth.js into:

`						JsonWebToken.sign({}, privateKey, {`

**Comment by Pesticles** [comment]
They're PEM format RSA, ie:
  "PRIVATE_KEY": "-----BEGIN RSA PRIVATE KEY-----\nMII...SU\n-----END RSA PRIVATE KEY-----\n",
  "PUBLIC_KEY": "-----BEGIN PUBLIC KEY-----\nMIG...AB\n-----END PUBLIC KEY-----\n",

**Comment by noyceguy** [comment]
Thank you for opening this issue. We are working on updating the code and instructions on this step.

**Comment by noyceguy** [comment]
Thank you for the feedback and questions on the private and public key pairs.
The documentation has been updated based on this feedback below:

https://github.com/aws-samples/lambdaedge-openidconnect-samples/blob/master/docs/keypairs.md
https://github.com/aws-samples/lambdaedge-openidconnect-samples/blob/master/docs/configuration.md#example-document-manually-created

Also, we have developed a CLI utility that will generate the configuration document including the private and public key pairs:
https://github.com/aws-samples/lambdaedge-openidconnect-samples/tree/master/cli

Please let us know if there are any other questions and we can open another issue.
Closing this issue for now.
