### ISSUE TITLE
Parameter overrides syntax needs to be updated

### ISSUE THREAD

**Issue by ashishgore** [aws-samples/lambdaedge-openidconnect-samples#23]
SAM CLI parameter overrides syntax was changed few releases back and needs to be updated to follow the ParameterKey,ParameterValue syntax.

```console
sam --version
SAM CLI, version 1.37.0

sam deploy \
 --template-file build/packaged.yaml \
 --stack-name oidc-auth \
 --capabilities CAPABILITY_NAMED_IAM \
 --parameter-overrides ParameterKey=BucketName,ParameterValue=${YOUR_NEW_STATIC_SITE_BUCKET_NAME} ParameterKey=LogBucketName,ParameterValue=${YOUR_LOG_BUCKET_NAME} ParameterKey=SecretKeyName,ParameterValue=${YOUR_SECRETS_MANAGER_KEY_NAME}
```

**Comment by noyceguy** [comment]
@ashishgore Thank you for the feedback. We will look at making these updates accordingly and will reply back here with any updates.

**Comment by noyceguy** [comment]
@ashishgore I am closing this issue for now. Please upgrade to the latest version of the AWS SAM CLI *1.65.0* as the new syntax does not require commas in between key value pairs. Please let me know if there are still errors and we will re-open this issue.
