### ISSUE TITLE
Nodejs version needs to be updated

### ISSUE THREAD

**Issue by ashishgore** [aws-samples/lambdaedge-openidconnect-samples#24]
nodejs version in the template.yaml file needs to be updated from nodejs10.x to nodejs14.x

**Comment by tchinchow** [comment]
I believe this is fixed by commit https://github.com/aws-samples/lambdaedge-openidconnect-samples/commit/ebc38a1b267c0e33390ad1988c0db6bcd256880c

**Comment by noyceguy** [comment]
This has been updated to the latest. Thank you for opening this issue
