### ISSUE TITLE
Please provide sample code for keycloak

### ISSUE THREAD

**Issue by stijnvanrenterghem** [aws-samples/lambdaedge-openidconnect-samples#35]
Please provide sample code for keycloak.
I would love to see a similar blogpost of this solution with keycloak. We can also work together on a blogpost.

**Comment by noyceguy** [comment]
@stijnvanrenterghem Thank you for the feedback. We can certainly add some details around how to set up this solution using keycloak. We will add this to our roadmap and see about writing a follow-up blog post.

**Comment by noyceguy** [comment]
@stijnvanrenterghem thank you for your request. We have included some base documentation on how to integrate this solution with Keycloak. Please refer to the documentation found here:
https://github.com/aws-samples/lambdaedge-openidconnect-samples/blob/master/docs/keycloak.md

Let us know if you have any other questions!
