### ISSUE TITLE
The function code size is larger than the maximum allowed size for functions that are triggered by a CloudFront event

### ISSUE THREAD

**Issue by workflo** [aws-samples/lambdaedge-openidconnect-samples#47]
Hi there,

we are trying to get this example app running but are unable to _deploy_, because the resulting Lambda function is too large.

> Resource handler returned message: "Invalid request provided: AWS::CloudFront::Distribution: The function code size is larger than the maximum allowed size for functions that are triggered by a CloudFront event: 1212049 Max allowed: 1048576 Function: arn:aws:lambda:us-east-1:xxxxxxxxxxx:function:yyyyyyyyyyyyyyyyyyyyyy-CloudFrontAuthFunction-wykPqdDXOu0C:1 (Service: CloudFront, Status Code: 400, Request ID: ...

![image](https://user-images.githubusercontent.com/1273522/211016448-bdbbdace-c9ca-4745-add8-6496fc7931cb.png)

We didn't touch the JS code nor the `package.json` file.

Can anyone reproduce this? What can we do?

Thanks in advance,
Florian.

**Comment by workflo** [comment]
At least we could verify that the code works after "manually" removing a bunch of unnecessary files between _build_ and _package_:

```
	find build/CloudFrontAuthFunction/node_modules -iname '*.d.ts' -delete
	find build/CloudFrontAuthFunction/node_modules -iname '*.md' -delete
	find build/CloudFrontAuthFunction/node_modules -iname '*.txt' -delete
	find build/CloudFrontAuthFunction/node_modules -iname 'license' -delete
	rm -r `find build/CloudFrontAuthFunction/node_modules -name "test" -type d`
	rm -r build/CloudFrontAuthFunction/node_modules/axios/dist
```

**Comment by noyceguy** [comment]
@workflo Thank you for opening this issue. We will work on condensing the node_modules to meet the limitations on the function size.

**Comment by noyceguy** [comment]
@workflo and @concordion2k thank you for opening-up this issue. Let me know if there are still any issues after doing the following:

1. Pull the latest from the `master` branch by running `git pull`.
2. Delete your existing `build` directory.
3. Re-run the deployment steps outlined in the README

Let me know if you have any questions!
